### ISSUE TITLE
Runtime error in vulkan

### ISSUE THREAD

**Issue by Dr-42** [TwentyFiveSoftware/ray-tracing-gpu-vulkan#1]
The code on successful compilation throws a vk::OutOfDateError

`
terminate called after throwing an instance of 'vk::OutOfDateKHRError'
  what():  vk::Queue::presentKHR: ErrorOutOfDateKHR
`

**Comment by TwentyFiveSoftware** [comment]
Can't reproduce, sorry. Feel free to reopen this issue if you can provide more information.
